///<reference path="utils.ts"/>
const items = {
    Kings_cavalary_shield: new Item({
        ID: 1,
        theName: "King's cavalary shield",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Iceborn_shield: new Item({
        ID: 2,
        theName: "Iceborn shield",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Staff_of_Homa: new Item({
        ID: 3,
        theName: "Staff of Homa",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Mistsplitter_reforged: new Item({
        ID: 4,
        theName: "Mistsplitter reforged",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Kings_cavalary_helmet: new Item({
        ID: 5,
        theName: "King's cavalary helmet",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.HELMET,
    }),
    Dragonskin_helmet: new Item({
        ID: 6,
        theName: "Dragonskin helmet",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.HELMET,
    }),
    Kings_cavalary_cuirass: new Item({
        ID: 7,
        theName: "King's cavalary cuirass",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Dragonskin_carapace: new Item({
        ID: 8,
        theName: "Dragonskin carapace",
        itemRarity: ITEM_RARITY.RARE,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Wooden_troll_shield: new Item({
        ID: 9,
        theName: "Wooden troll shield",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Private_soldiers_shield: new Item({
        ID: 10,
        theName: "Private soldier's shield",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Wooden_helmet: new Item({
        ID: 11,
        theName: "Wooden helmet",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.HELMET,
    }),
    Iron_soldiers_helmet: new Item({
        ID: 12,
        theName: "Iron soldier's helmet",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.HELMET,
    }),
    Cudgel_of_negotiations: new Item({
        ID: 13,
        theName: "Cudgel of negotiations",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Battered_soldier_sword: new Item({
        ID: 14,
        theName: "Battered soldier sword",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Old_leather_armor: new Item({
        ID: 15,
        theName: "Old leather armor",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Private_soldier_cuirass: new Item({
        ID: 16,
        theName: "Private soldier's cuirass",
        itemRarity: ITEM_RARITY.COMMON,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Steel_shield: new Item({
        ID: 17,
        theName: "Steel shield",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Spiked_shield: new Item({
        ID: 18,
        theName: "Spiked shield",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Claymore: new Item({
        ID: 19,
        theName: "Claymore",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Light_blessed_bow: new Item({
        ID: 20,
        theName: "Light blessed bow",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Horned_helmet: new Item({
        ID: 21,
        theName: "Horned helmet",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.HELMET,
    }),
    Ornate_hood: new Item({
        ID: 22,
        theName: "Ornate hood",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.HELMET,
    }),
    Spiked_armor: new Item({
        ID: 23,
        theName: "Spiked armor",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Priests_robe: new Item({
        ID: 24,
        theName: "Priest's robe",
        itemRarity: ITEM_RARITY.UNCOMMON,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Shield_of_nameless_hero: new Item({
        ID: 25,
        theName: "Shield of nameless hero",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Dragonbone_shield: new Item({
        ID: 26,
        theName: "Dragonbone shield",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.SHIELD,
    }),
    Weapon_of_nameless_hero: new Item({
        ID: 27,
        theName: "Weapon of nameless hero",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Dragoons_spear: new Item({
        ID: 28,
        theName: "Dragoon's spear",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.WEAPON,
    }),
    Helmet_of_nameless_hero: new Item({
        ID: 29,
        theName: "Helmet of nameless hero",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.HELMET,
    }),
    Dragoons_Helm: new Item({
        ID: 30,
        theName: "Dragoon's Helm",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.HELMET,
    }),
    Armor_of_nameless_hero: new Item({
        ID: 31,
        theName: "Armor of nameless hero",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.ARMOR,
    }),
    Dragoons_armor: new Item({
        ID: 32,
        theName: "Dragoon's armor",
        itemRarity: ITEM_RARITY.LEGENDARY,
        itemType: ITEM_TYPE.ARMOR,
    }),
};

let itemsList = Utils.CreateMap(items);